# Generated by Django 4.2.3 on 2023-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('liverpool', 'Liverpool')], default='', max_length=200),
        ),
    ]
