# Generated by Django 4.2.3 on 2023-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('liverpool', 'Liverpool'), ('manchester', 'Manchester')], default='', max_length=200),
        ),
    ]
