# Generated by Django 4.2.3 on 2023-07-10 18:47

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mortgage_deal_expiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
